### ISSUE TITLE
no reversion.VersionAdmin class available?

### ISSUE THREAD

**Issue by stevejalim** [etianen/django-reversion#100]
Following the Admin integration tutorial:

```
import reversion
class MyCustomAdmin(reversion.VersionAdmin):
    pass
admin.site.register(SomeModel, MyCustomAdmin)
```

raises an AttributeError:

```
'module' object has no attribute 'VersionAdmin'
```

Indeed, inspecting the package confirms there is no VersionAdmin class accessible from a top-level import of 'reversion'.

What am I missing here? I've had good times with an earlier release of reversion.

(Django 1.2.7, django-reversion installed into a virtualenv with pip)

**Comment by macropin** [comment]
I think there may be a regression here with the latest release (1.10.1). Using `1.9.3` works.

```
(ve27)[root@114bc55af404 git]# ./manage.py 
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/ve27/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/ve27/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/srv/ve27/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/ve27/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/srv/ve27/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/srv/ve27/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/srv/ve27/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/ve27/lib/python2.7/site-packages/dnsmanager/admin.py", line 43, in <module>
    class ZoneAdmin(reversion.VersionAdmin):
AttributeError: 'module' object has no attribute 'VersionAdmin'
```

**Comment by etianen** [comment]
Check the changelog:

https://github.com/etianen/django-reversion/blob/master/CHANGELOG.md#110---02122015

**Comment by macropin** [comment]
Thanks!

**Comment by etianen** [comment]
No worries! Django 1.9's changes to app loading meant it became impossible
to include top-level shortcuts to a lot of the reversion functionality. The
only solution was a lot of breaking changes. :(
