### ISSUE TITLE
ImportError: No module named defaults

### ISSUE THREAD

**Issue by victorhooi** [etianen/django-reversion#202]
Hi,

I'm trying to run django-reversion against the latest Django, and I'm hitting an error about `No module named defaults`:

```
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/victorhooi/code/fantasiapos/fantasiapos/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/victorhooi/code/fantasiapos/pos/admin.py", line 2, in <module>
    from reversion.admin import VersionAdmin
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django-reversion/src/reversion/__init__.py", line 12, in <module>
    from reversion.admin import VersionAdmin
  File "/Users/victorhooi/.virtualenvs/fantasiapos/src/django-reversion/src/reversion/admin.py", line 6, in <module>
    from django.conf.urls.defaults import patterns, url
ImportError: No module named defaults
```

I thinking this might be related to the change in Django 1.4 (https://docs.djangoproject.com/en/dev/releases/1.4/), which saw django.conf.urls.defaults moved to django.conf.urls?

Cheers,
Victor

**Comment by oppianmatt** [comment]
I'm getting this with the upgrade to django reversion 1.8.3

```
(venv)(venv) matt@Cronus[/Users/matt/Source/Pitchup.com]$ ./manage.py shell
Using settings: pitchup.settings.local
Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/reversion/__init__.py", line 11, in <module>
    from reversion.revisions import default_revision_manager, revision_context_manager, VersionAdapter
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/reversion/revisions.py", line 21, in <module>
    from reversion.models import Revision, Version, has_int_pk, pre_revision_commit, post_revision_commit
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/reversion/models.py", line 6, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
ImportError: No module named fields
```

**Comment by etianen** [comment]
What version of Django are you using? And is there any reason you’re not using django-reversion 1.8.6?
