### ISSUE TITLE
Problems with Django 1.8 and UUIDField

### ISSUE THREAD

**Issue by aidanlister** [etianen/django-reversion#409]
```
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/aidan/.virtualenvs/abas-web/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/aidan/.virtualenvs/abas-web/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/aidan/.virtualenvs/abas-web/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/aidan/.virtualenvs/abas-web/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/aidan/.virtualenvs/abas-web/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/aidan/Sites/abas-web/abas/apps/properties/models.py", line 221, in <module>
    class Property(TrackedModel):
  File "/Users/aidan/Sites/abas-web/abas/apps/properties/models.py", line 236, in Property
    guid = models.UUIDField(blank=True, unique=True, default=uuid.uuid4)
AttributeError: 'module' object has no attribute 'UUIDField'
```

This goes away if I drop the @reversion.register decorator.

**Comment by aidanlister** [comment]
Looks like some of my commands were being pushed to a container that hadn't been updated and was still running Django 1.7
