### ISSUE TITLE
Problem with contenttypes

### ISSUE THREAD

**Issue by marctc** [etianen/django-reversion#412]
I want to use django-reversion in a project with Django 1.8. When I try to run migrate command, the output shows me this error message:

RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.

I only found this thread discussing about a similar issue:
https://groups.google.com/forum/#!msg/django-users/DlRQOdsJL6o/IbN_1Cjjyz8J

I am doing something wrong? I used django-reversion in other projects and never caused me any troubles.

**Comment by etianen** [comment]
Do you have a complete stack trace?

**Comment by marctc** [comment]
marc@apsl ~/workspace/aploy/src$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, grappelli, messages, django_extensions, apconf
  Apply all migrations: sessions, admin, deploy, sites, auth, reversion, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 225, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 82, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/home/marc/virtualenvs/aploy/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 78, in get_for_model
    "Error creating new content types. Please make sure contenttypes "
RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.

If I remove 'reversion' from installed_apps, migrate works properly.

**Comment by etianen** [comment]
Was a resolution reached on this?

**Comment by fe01134** [comment]
I am hitting the same problem.

**Comment by sachinvettithanam** [comment]
i found issue occered due to 
Fixed #24099 -- Removed contenttype.name deprecated field

try remove it manually:
ALTER TABLE django_content_type DROP COLUMN name

My issue was resolved.
