### ISSUE TITLE
Is it possible to get a set of objects for a specific version or date?

### ISSUE THREAD

**Issue by nopium** [etianen/django-reversion#417]
Something like this:

results = YourModel.objects.get_for_date(datetime.datetime(2008, 7, 10)).filter(status=paid)

**Comment by etianen** [comment]
If you create a reverse generic relation from your model to the Version object, you can query along that relation.

So, add something like:

versions = GenericRelation(Version)

Then you can query like:

YourModel.objects.filter(versions__revision__date_created=something)

**Comment by nopium** [comment]
Thanks for suggestion!

FieldError: Cannot resolve keyword 'versions' into field

Am I missing something there?

**Comment by etianen** [comment]
Yes. :)

Can you post a full trace back?

**Comment by nopium** [comment]
My model is:

```
from django.contrib.contenttypes.fields import GenericRelation
from reversion.models import Version

class Income(AbstractModel):
      ...a bunch of fields...
      versions = GenericRelation(Version)
```

I am trying to make a request:
```
Income.objects.filter(versions__revision__date_created=prev_version_time)
```

And get this error:
```
======================================================================
ERROR: test_create_income_version (contracts.tests.test_version.VersionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "myapp/contracts/tests/test_version.py", line 31, in test_create_income_version
    Income.objects.filter(versions__revision__date_created=prev_version_time).aggregate(prev_total_count=Count('id'))
  File "myapp/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "myapp/env/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "myapp/env/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "myapp/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1304, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "myapp/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1331, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "myapp/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1144, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "myapp/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1030, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "myapp/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'versions' into field. Choices are: category, cfo, cfo_id, contr_str, contract, contract_id, contragent, contragent_id, date, date_str, history, id, in_number, in_value, in_value_orig, income, is_confirmed, is_deleted, is_presale, jira_title, manager, month, operation, orig_income, orig_income_id, out_value, project, project_id, purpose, skip_tax, user, user_id

```

**Comment by etianen** [comment]
I would have thought that would work. Looking at the Django docs, however, it doesn’t seem to be supported: https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#reverse-generic-relations
