### ISSUE TITLE
DoesNotExits Issue

### ISSUE THREAD

**Issue by pranto157** [etianen/django-reversion#421]
```
Traceback (most recent call last):
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/django/contrib/admin/views/decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "/Users/newscred/personal/ssca/app_backoffice/views/membership.py", line 872, in edit_account
    reversion.set_user(request.user)
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/reversion/revisions.py", line 291, in __exit__
    self._context_manager.end()
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/reversion/revisions.py", line 177, in end
    in manager_context.items()
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/reversion/revisions.py", line 176, in <genexpr>
    for obj, data
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/reversion/revisions.py", line 594, in <lambda>
    version_data = lambda: adapter.get_version_data(instance, VERSION_ADD, self._revision_context_manager._db)
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/reversion/revisions.py", line 108, in get_version_data
    "serialized_data": self.get_serialized_data(obj),
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/reversion/revisions.py", line 91, in get_serialized_data
    fields = list(self.get_fields_to_serialize()),
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 99, in serialize
    s.serialize(queryset, **options)
  File "/Users/newscred/personal/ssca/env/src/wadofstuff-django-serializers/wadofstuff/django/serializers/base.py", line 71, in serialize
    self.handle_related_fk_field(obj, field_name)
  File "/Users/newscred/personal/ssca/env/src/wadofstuff-django-serializers/wadofstuff/django/serializers/python.py", line 190, in handle_related_fk_field
    related = getattr(obj, fname)
  File "/Users/newscred/personal/ssca/env/lib/python2.7/site-packages/django/db/models/fields/related.py", line 279, in __get__
    raise self.related.model.DoesNotExist
DoesNotExist
```
Guys I am having the above issue Can anyone help ? BTW - here is my code block - 
```
with reversion.create_revision():
    reversion.set_user(request.user)
```
Django Version - Django==1.5.5

**Comment by etianen** [comment]
The model saved in the revision references another model via ForeignKey that no longer exists in the database. Because of this, the attempt to recover the model from the revision fails.
