### ISSUE TITLE
Getting NoReverseMatch with 1.9.3 on django-grappelli and django-suit

### ISSUE THREAD

**Issue by nemesisdesign** [etianen/django-reversion#445]
Hi,

I'm trying 1.9.3 and I get this exception when trying to revert a document:

    NoReverseMatch: Reverse for 'app_list' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'admin/(?P<app_label>hardware|profiles|layers|participation|mailing|net|default|nodes|links|cms|auth|connectors|notifications|metrics)/$']

It seems that the template gets a call like `reverse('admin:app_list', args=[], kwargs={}, current_app=None)` and this causes the exception.

I do not understand if there is something I have to change in my app in order to upgrade to 1.9.3 or if it might be a bug in django-reversion.

What do you think?

Best regards
Federico

**Comment by etianen** [comment]
Could you post the full traceback please?

**Comment by etianen** [comment]
Also, are have you overidden any of the django-reversion templates?

**Comment by etianen** [comment]
Also, are you certain you're using 1.9.3? This was an issue in 1.9.2, but should have been fixed.

**Comment by onyekaa** [comment]
Just installed this (1.9.3) for the first time, and I'm getting the same error.

**Comment by onyekaa** [comment]
Full traceback. It seems to fail around the `request.render()` line in the `revisionform_view` function
```
[29/Aug/2015 15:36:03] ERROR [django.request:256] Internal Server Error: /admin/people/person/10/history/5/
Traceback (most recent call last):
  File "/Users/xxx/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/xxx/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/xxx/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/xxx/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/xxx/lib/python2.7/site-packages/reversion/admin.py", line 214, in revision_view
    "title": _("Revert %(name)s") % {"name": version.object_repr},
  File "/Users/xxx/lib/python2.7/site-packages/reversion/admin.py", line 191, in revisionform_view
    response.render()  # Eagerly render the response, so it's using the latest version of the database.
  File "/Users/xxx/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/xxx/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Users/xxx/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/xxx/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/xxx/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'app_list' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'admin/(?P<app_label>sites|review|watermarker|account|company|title|users|socialaccount|cities_light|auth|notifications|django_messages|people)/$']
```

**Comment by etianen** [comment]
Hi,

Could you let me know the following?

- Your version of Django
- With TEMPLATE_DEBUG mode on, the line of the template file that's causing the error?

**Comment by onyekaa** [comment]
Django 1.8.

The template sections:

```
        <a href="{% url 'admin:app_list' app_label=app_label %}">{{app_label|capfirst|escape}}</a> &rsaquo;
        <a href="{% url opts|admin_urlname:'changelist' %}">{{opts.verbose_name_plural|capfirst}}</a> &rsaquo;
        <a href="{% url opts|admin_urlname:'change' object_id %}">{{original|truncatewords:"18"}}</a> &rsaquo;
        <a href="{% url opts|admin_urlname:'history' object_id %}">{% trans "History" %}</a> &rsaquo;
```

From what I could see in the debug_toolbar, it looks like in those circumstances it doesn't receive the opts variables.

**Comment by etianen** [comment]
Which template file is it?

**Comment by onyekaa** [comment]
revision_form.html

**Comment by etianen** [comment]
And, to confirm, this is the revision_form.html that ships with reversion?

**Comment by etianen** [comment]
Okay, here's something I'd like you to debug. In reversion/admin.py, can
you replace line 190:

response.template_name = template_name  # Set the template name to the
correct template.

With:

print(request.method)
print(response.status_code)
print(response.template_name)
response.template_name = template_name  # Set the template name to the
correct template.

Then let me know what gets logged to console?

**Comment by onyekaa** [comment]
Okay, I took a look at this again, seems like my issue is coming from django suit. Not sure why. Even if I copy and paste the code from the one that ships with reversion, it doesn't work. I literally have to rename the file to get it to use reversion's file and thus, work. Is there something I can set it to force it to use the file that comes with this app?

**Comment by etianen** [comment]
Does Django-suit come with some specific reversion templates, then?

I'll take a look at this tomorrow, and if necessary get a pull request in
for Django-suit urgently.

**Comment by etianen** [comment]
I've just raised a PR with django-suit. Let's hope they integrate it soon.

Meanwhile, feel free to patch your django-suit installation with the PR here: https://github.com/darklow/django-suit/pull/424

**Comment by nemesisdesign** [comment]
Hi @etianen,

now I understand!

Here's my problem (i'm using grappelli):
https://github.com/sehmaschine/django-grappelli/tree/master/grappelli/templates/reversion

Could you point me to the relevant bits that changed in reversion? I can try to send a PR to @sehmaschine asap.

**Comment by etianen** [comment]
Here's the diff of the templates changes, here:

https://github.com/darklow/django-suit/pull/424/files

Very easy, really.

**Comment by onyekaa** [comment]
@etianen  Yeah it does, sorry for my slow reply. Will test this, but it seems you've already got it sorted.

**Comment by etianen** [comment]
I've just submitted a PR to the grappelli repo. Hopefully they'll notice soon. :)

**Comment by etianen** [comment]
This is now merged with grappelli, which is a nice fast response. :D

**Comment by nemesisdesign** [comment]
Wow that was fast, THANKS :+1:

**Comment by nemesisdesign** [comment]
I think there's a problem in ``change_list.html`` with the recovery deleted pages link (django 1.8, reversion 1.9.3, grappelli 2.7.1).

On django-grappelli it seems ``{{ recoverlist_url }}`` is evaluated as empty:
https://github.com/etianen/django-reversion/blob/master/src/reversion/templates/reversion/change_list.html

Is that possible?

**Comment by nemesisdesign** [comment]
if the empty ``{{ recoverlist_url }}`` issue is correct, there might be a similar issue in the breadcrumbs:

````
{% block breadcrumbs %}
    {% if not is_popup %}
        <ul>
            <li><a href="{% url 'admin:index' %}">{% trans "Home" %}</a></li>
            <li><a href="{% url 'admin:app_list' app_label %}">{% trans app_label|capfirst|escape %}</a></li>
            <li><a href="{{ changelist_url }}">{% trans opts.verbose_name_plural|capfirst %}</a></li>
            <li><a href="{{ change_url }}">{{ original|truncatewords:"18" }}</a></li>
            <li><a href="../">{% trans "History" %}</a></li>
            <li>{% blocktrans with opts.verbose_name as verbose_name %}Revert {{ verbose_name }}{% endblocktrans %}</li>
        </ul>
    {% endif %}
{% endblock %}
```

In this case the empty vars are `{{ changelist_url }}` and `{{ change_url }}`.

**Comment by etianen** [comment]
Damn. I'll take a look at this first thing tomorrow.

**Comment by nemesisdesign** [comment]
I temporarily resolved my issue by adding custom templates and replacing empty vars with relative links.

https://github.com/ninuxorg/nodeshot/commit/b7e7e2f5eacc43fad529b586a6b85e63357edad7

I tried using the syntax of templates present in django-reversion's master (opts|admin_url ...) but it raises an exception and I'm not familiar enough with it to understand if it depends on my project settings or not.

However, I'd like to remove the custom templates once the next django-grappelli version is released, so if you have any suggestion which I could try I'll be happy to give it a go.

**Comment by etianen** [comment]
This pull request shows the changed needed to the django-grappelli templates to work with the latest reversion.

https://github.com/sehmaschine/django-grappelli/pull/663/files

Or, just pip install the github master of django-grappelli

**Comment by nemesisdesign** [comment]
Oh, I was missing `{% load i18n admin_urls %}`, I don't know why I didn't figure it out, but thanks.
