### ISSUE TITLE
AppRegistryNotReady starting Django 1.9a1

### ISSUE THREAD

**Issue by dpoirier** [etianen/django-reversion#454]
I started testing our app with Django 1.9a1 and immediately hit this. It might be due to (indirectly) importing models from __init__.py.

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
        utility.execute()
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/core/management/__init__.py", line 324, in execute
        django.setup()
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/apps/registry.py", line 86, in populate
        app_config = AppConfig.create(entry)
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
        module = import_module(entry)
      File "<VIRTUALENV>/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "<VIRTUALENV>/lib/python3.4/site-packages/reversion/__init__.py", line 11, in <module>
        from reversion.revisions import default_revision_manager, revision_context_manager, VersionAdapter
      File "<VIRTUALENV>/lib/python3.4/site-packages/reversion/revisions.py", line 18, in <module>
        from django.contrib.contenttypes.models import ContentType
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
        class ContentType(models.Model):
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
        app_config = apps.get_containing_app_config(module)
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/apps/registry.py", line 240, in get_containing_app_config
        self.check_apps_ready()
      File "<VIRTUALENV>/lib/python3.4/site-packages/django/apps/registry.py", line 125, in check_apps_ready
        raise AppRegistryNotReady("Apps aren't loaded yet.")
    django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by etianen** [comment]
What code is causing this issue?

**Comment by dpoirier** [comment]
Just having 'reversion' in `INSTALLED_APPS` seems to trigger it.  Here's a little shell script that reproduces it consistently:

    #!/bin/bash

    set -ex

    rm -rf testenv testreversion
    virtualenv -p /usr/bin/python3.4 testenv
    . testenv/bin/activate
    pip install --pre Django==1.9a1
    pip install django-reversion==1.9.3
    pip freeze
    django-admin.py startproject testreversion
    sed -e "s/INSTALLED_APPS = \\[/INSTALLED_APPS = ['reversion',/g" <testreversion/testreversion/settings.py >tmp.py
    mv tmp.py testreversion/testreversion/settings.py
    python testreversion/manage.py shell

**Comment by etianen** [comment]
Oh, damn. It looks like in Django 1.9 I can no longer load any models on
app startup.

This is going to need a silly workaround.

**Comment by etianen** [comment]
Try the master branch.

If you use the low-level API, pay particular attention to:
http://django-reversion.readthedocs.org/en/latest/api.html

You'll all need to import VersionAdmin from reversion.admin

Basically, I had to remove all the reversion.something() shortcuts. I'm not
sure that there's any way to do this in a backwards-compatible manner. :(

**Comment by dpoirier** [comment]
Using master got me past that problem, once I updated my code to import VersionAdmin from reversion.admin.

**Comment by mikaelengstrom** [comment]
@etianen, When are you planing on doning a 1.9 compatible release?

**Comment by etianen** [comment]
Coincidentally, I'm doing it right now! Just waiting for the Travis build
to complete without errors before pushing!

**Comment by mikaelengstrom** [comment]
Awesome! Thanks! :+1:
