### ISSUE TITLE
AttributeError: 'module' object has no attribute 'register'

### ISSUE THREAD

**Issue by tilaprimera** [etianen/django-reversion#466]
In the models, I tried to register my model Vendor, 
 
    from reversion import revisions
    revisions.register(Vendor)

And, when I try, 

    ./manage.py runserver

    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/core/management/__init__.py",    
    line 338, in execute_from_command_line
    utility.execute()
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/core/management/__init__.py", 
    line 312, in execute
    django.setup()
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/apps/registry.py", line 108, in  
    populate
    app_config.import_models(all_models)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/apps/config.py", line 198, in 
    import_models
    self.models_module = import_module(models_module_name)
    File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
    File "/home/tilaprimera/PycharmProjects/tp/inventory/models/__init__.py", line 3, in <module>
    import models
    File "/home/tilaprimera/PycharmProjects/tp/inventory/models/models.py", line 909, in <module>
    revisions.register(Vendor)
    AttributeError: 'module' object has no attribute 'register'

The installed packages are the following. 

    Django (1.8.3)
    django-reversion (1.9.3)

**Comment by tilaprimera** [comment]
Manually I registered my model via, manually 

    revisions.default_revision_manager.register(Vendor)

**Comment by etianen** [comment]
How you access the low-level API differs depending on your Django version.

http://django-reversion.readthedocs.org/en/latest/api.html#api

**Comment by tilaprimera** [comment]
Using django version 1.8.1
