### ISSUE TITLE
Upgrade from 1.8 to 1.9: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by kierun** [etianen/django-reversion#481]
I have a project that uses Django 1.8 and reversion 1.9.3.  I want to upgrade to Django 1.9, so I ran the `pip install -U ...` commands, looked at the release notes for changes I need to make, then run `check`. However, I get this error:

    python manage.py check -v 3
    Traceback (most recent call last):
      File "manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
        django.setup()
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
        module = import_module(entry)
      File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/usr/repos/intranet/org_intranet_site/organisations/__init__.py", line 3, in <module>
        from models import Supplier
      File "/home/usr/repos/intranet/org_intranet_site/organisations/models/__init__.py", line 15, in <module>
        from .address import Address
      File "/home/usr/repos/intranet/org_intranet_site/organisations/models/address.py", line 8, in <module>
        from .abstract import Abstract
      File "/home/usr/repos/intranet/org_intranet_site/organisations/models/abstract.py", line 13, in <module>
        from reversion import revisions as reversion
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/reversion/revisions.py", line 18, in <module>
        from django.contrib.contenttypes.models import ContentType
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
        class ContentType(models.Model):
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
        app_config = apps.get_containing_app_config(module)
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
        self.check_apps_ready()
      File "/home/usr/Envs/intranet/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
        raise AppRegistryNotReady("Apps aren't loaded yet.")
    django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

Any idea what I am doing wrong?

**Comment by kierun** [comment]
Note that if I downgrade Django from 1.9.1 to 1.8.7, then the `check` command works. However, some of my unit tests using reversion fail with:

    AttributeError: 'module' object has no attribute 'get_for_object'

Although, I assume that's my fault for not updating them to the new API. ☺

**Comment by claudep** [comment]
This is not a reversion issue. In Django 1.9, you shouldn't import models from your app's `__init__.py` file.

**Comment by kierun** [comment]
☺ Well, that's me feeling well sheepish right about now.  Thank you for your help!
