### ISSUE TITLE
save() method without creating revision for some cases

### ISSUE THREAD

**Issue by Egregors** [etianen/django-reversion#505]
Hi. At first, thanks for you project, it absolutely amazing.

I have a question: How can I save model instance without creating revision?
For example, say I have this model (plus, I user Admin revision integration):
```
class Item(models.Model):
    title = models.CharField(max_length=255)
    views = models.PositiveIntegerField(default=0)

reversion.register(Item)
```
and every time, when somebody open page with this Item I increment `views`:

```
    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        item.views += 1
        item.save()
        context['item'] = item
        return context
```

I don't wont actually create revision in this case, because this is redundant and danger for DB space and DB performance. By the way, revision will create even `exclude=['views']` is set. 

P.S.
Do you know, 1.10.1 version in this repo, and 1.10.1 in PIPY is different? 
Right now 1.10.1 in PIPY contain compatibility errors for py3.

**Comment by etianen** [comment]
What compatibility errors are in the 1.10.1 PyPi version?

To fix your actual question, are you using RevisionMiddleware? If you are,
I'd really recommend not, and manually marking up blocks of code using the
create_revision() decorator.

**Comment by Egregors** [comment]
Thanks for quickly reply.

> What compatibility errors are in the 1.10.1 PyPi version?

`django-reversion-1.10.1/src/reversion/management/commands`
reduce func, for example:

```
manage.py@retail > deleterevisions catalog
bash -cl "/Users/egregors/Documents/Bitbucket/retail/env/bin/python3 /Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py deleterevisions catalog /Users/egregors/Documents/Bitbucket/retail"
/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.5/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.5/site-packages/cities_light/contrib/restframework3.py:127: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^', include(router.urls)),

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 182, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/egregors/Documents/Bitbucket/retail/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.5/site-packages/reversion/management/commands/deleterevisions.py", line 132, in handle
    subqueries = reduce(operator.or_, subqueries)
NameError: name 'reduce' is not defined

Process finished with exit code 1
```

> To fix your actual question, are you using RevisionMiddleware?

Yep. Ok. Last question: Will Admin Integration work, if I turn off RevisionMiddleware?

**Comment by etianen** [comment]
Admin integration does not use RevisionMiddleware, so you're safe.

You're right about the PyPi version. I'm so confused!

Meanwhile 1.10.2 is the correct code... use that!

**Comment by Egregors** [comment]
> Admin integration does not use RevisionMiddleware, so you're safe.

Nice! I'll try solve the problem without RevisionMiddleware. Thanks for answers.
