### ISSUE TITLE
Specified key was too long in initial migration

### ISSUE THREAD

**Issue by dani0805** [etianen/django-reversion#531]
While installing on mysql 5.6.30, django 1.8.5.
encoding utf8mb4 collation utf8mb4_unicode_ci

I run into this exception

Running migrations:
  Rendering model states... DONE
  Applying reversion.0001_initial...Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/medis-test/workspace/medis/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 91, in __exit__
    self.execute(sql)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/medis-env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

**Comment by etianen** [comment]
Try running:

./manage.py migrate reversion --run-syncdb
./manage.py migrate reversion --fake

The issue you're experiencing was fixed in a later migration.
django-reversion 1.11.0 (released next week) comes with a replacement
initial migration that fixes the issue completely, but this workaround will
do for now.

(It's due to certain MySQL character encodings taking up more space,
limiting the size of indexes)

**Comment by dani0805** [comment]
thanks! Will do in the future. Good to know the problem is solved, I figure it had to do with the 4 bytes utf, blame it on our users who put emoji in the text

I already solved by using:
 
SET GLOBAL innodb_file_per_table = ON,
           innodb_file_format = Barracuda,
           innodb_large_prefix = ON;
ALTER TABLE reversion_revision
    ROW_FORMAT = DYNAMIC;
ALTER TABLE reversion_version
    ROW_FORMAT = DYNAMIC;

**Comment by shtalinberg** [comment]
This work only for ENGINE = InnoDB

SET GLOBAL innodb_file_per_table = ON,
innodb_file_format = Barracuda,
innodb_large_prefix = ON;
ALTER TABLE `reversion_revision` ENGINE = InnoDB;
ALTER TABLE `reversion_version` ENGINE = InnoDB;
ALTER TABLE reversion_revision ROW_FORMAT = DYNAMIC;
ALTER TABLE reversion_version ROW_FORMAT = DYNAMIC;

**Comment by alantygel** [comment]
Hi,

I'm running into the same problem and none of the solutions above worked.

I'm at MariaDB 5.5.0. Is this database supported?

**Comment by etianen** [comment]
I've not tested against MariaDB 5.5.0. That sounds pretty old, given that the latest release is 10.x

I suspect your database encoding is wrong in some way, but I'm not a MySQL expert.

**Comment by alantygel** [comment]
Ops, I'm sorry, I've misread the version.
My MariaDB version is 10.0.36.
