### ISSUE TITLE
Migration exceptions

### ISSUE THREAD

**Issue by sweaver360** [etianen/django-reversion#537]
I just upgraded to the latest version of reversion after being on 1.10.x.  When attempting to run migration 3, I got the following error:

Running migrations:
  Applying reversion.0003_auto_20160601_1600...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\commands\migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\migration.py", line 120, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\operations\special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "C:\Users\Scott\ve\lib\site-packages\reversion\migrations\0003_auto_20160601_1600.py", line 26, in de_dupe_version_table
    pk__in=keep_version_ids,
  File "C:\Users\Scott\ve\lib\site-packages\django\db\models\query.py", line 600, in delete
    deleted, _rows_count = collector.delete()
  File "C:\Users\Scott\ve\lib\site-packages\django\db\models\deletion.py", line 292, in delete
    count = qs._raw_delete(using=self.using)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\models\query.py", line 614, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\models\sql\subqueries.py", line 81, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\models\sql\compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\mysql\base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Scott\ve\lib\site-packages\MySQLdb\cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\Scott\ve\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1093, "You can't specify target table 'reversion_version' for update in FROM clause")

I then ran migrate again and now I get this every time:

  Applying reversion.0003_auto_20160601_1600...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Scott\ve\lib\site-packages\django\core\management\commands\migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\migrations\operations\fields.py", line 121, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\base\schema.py", line 438, in remove_field
    self.execute(sql)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\base\schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Scott\ve\lib\site-packages\django\db\backends\mysql\base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Scott\ve\lib\site-packages\MySQLdb\cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\Scott\ve\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1091, "Can't DROP 'manager_slug'; check that column/key exists")

Thanks.

**Comment by etianen** [comment]
Unfortunately, MySQL doesn't provide transaction support for schema
changes, so your database is now in an inconsistent state. Let's try to
rescue that!

./manage.py migrate reversion 0003 --fake

./manage.py dbshell
> UPDATE reversion_version SET db='default';

./manage.py migration reversion

As to the initial cause of the problem - it seems that MySQL doesn't like
the de-duplication migration, due to it performing a subquery on the table
it's deleting from. Never knew that! I'll push out another release that
addresses this for other people right now.

**Comment by sweaver360** [comment]
Thanks for the quick fix!  The migration worked this time without any issues.

**Comment by etianen** [comment]
Excellent! It's always annoying when an open source project does a big update and breaks everything, so I'm trying to jump on this stuff fast before it affects too many people! :D
