### ISSUE TITLE
Im beginner for the revision control, i wanted to add rollback and recovery to my admin site using django reversion.

### ISSUE THREAD

**Issue by guganselvaraj** [etianen/django-reversion#539]
Hi ,
Im beginner for the revision control, i wanted to add rollback and recovery to my admin site using django reversion. I followed the doc : https://django-reversion.readthedocs.io/en/stable/admin.html but im getting these errors ! can you please help me out solving it ! 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/eindhan/PROJECT-FALCON/falcon/falcon_app/admin.py", line 5, in <module>
    admin.site.register(User)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    raise AlreadyRegistered('The model %s is already registered' % model.__name__)
django.contrib.admin.sites.AlreadyRegistered: The model User is already registered
```

**Comment by guganselvaraj** [comment]
in my models.py i have the following ! : 

from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.contrib.auth.models import AbstractUser as AuthUser
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.utils.text import slugify
from django.db import models
from django.contrib import admin
from reversion.admin import VersionAdmin

class User(AuthUser): # pylint: disable=no-init
    # Default quota is 2GB
    quota = models.BigIntegerField(default=2147483648)
    api_key = models.CharField(max_length=10, default='')
    address = models.CharField(max_length=30, default='')
    address2 = models.CharField(max_length=30, default='')
    city = models.CharField(max_length=30, default='')
    country = models.CharField(max_length=30, default='')
    postalcode = models.CharField(max_length=10, default='' )
    stripe_customer_id = models.CharField(max_length=50, default='')
    stripe_subscription_id = models.CharField(max_length=50, default='')
    password_reset = models.BooleanField(default=False)
    stripe_plan_id = models.CharField(max_length=50, default='')

    def hquota(self, unit):
        if unit == 'MB':
            return self.quota/1048576.0
        elif unit == 'GB':
            return self.quota/1073741824.0
        else:
            return 'Unknown unit'

    def update_quota(self, new_quota):
        self.quota = self.quota + new_quota        
        
    @property
    def used_quota(self):
        used = User.objects.filter(username=self.username).aggregate(models.Sum('document__file_size'))['document__file_size__sum']
        if used:
            return used
        else:
            return 0

    @property
    def balance_quota(self):
        return self.quota - self.used_quota
    
    def __repr__(self):
        return ('''User(username="{}",password="{}",quota={})'''.format(self.username,
                                                                    self.password,
                                                                    self.quota))
@admin.register(User)
class YourModelAdmin(VersionAdmin):

    pass

**Comment by guganselvaraj** [comment]
am i doing anything wrong ???

**Comment by etianen** [comment]
That error is coming from your admin module. It looks like you're
registering the User model twice with the admin.

If you're trying to register the user model with django-reversion admin,
then you'll have to unregister it with the built-in model admin first.

https://django-reversion.readthedocs.io/en/stable/admin.html#integration-with-3rd-party-apps

**Comment by guganselvaraj** [comment]
can you please give me an example with the above code.... i want the User model to be registered for reversion control ! im quiet stuck !????

```
admin.site.unregister(User)

@admin.register(User)
class YourModelAdmin(VersionAdmin):

    pass

```
 is this right ??? or anything else needs to be done ???

**Comment by etianen** [comment]
```py
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin
from reversion.admin import VersionAdmin
```

admin.site.unregister(User

@admin.register(User)
class UserVersionAdmin(UserAdmin, VersionAdmin):

    pass

**Comment by etianen** [comment]
Oops, quick edit to fix formatting.

That should sort you.

**Comment by guganselvaraj** [comment]
After doing it !

i got this ! :-1: 
```

Traceback (most recent call last):
  File "falcon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/eindhan/PROJECT-FALCON/falcon/falcon_app/models.py", line 56, in <module>
    admin.site.unregister(User)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model User is not registered
(falcon) eindhan@eindhan:~/PROJECT-FALCON$ clear

(falcon) eindhan@eindhan:~/PROJECT-FALCON$ python falcon/manage.py 
Traceback (most recent call last):
  File "falcon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/eindhan/PROJECT-FALCON/falcon/falcon_app/models.py", line 56, in <module>
    admin.site.unregister(User)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model User is not registered

```

**Comment by etianen** [comment]
What is your INSTALLED_APPS setting?

**Comment by guganselvaraj** [comment]
INSTALLED_APPS = [
    'jfu',
    'pipeline',
    'falcon_app.apps.FalconAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', 
    'djstripe',
    'django.contrib.gis',
    'debug_toolbar',
    'reversion',
]
 is my installed apps in settings files !!!

**Comment by etianen** [comment]
Place your falcon app after the auth app. Should work then.

**Comment by guganselvaraj** [comment]
Nope its is not working yet ! same error is getting repeated ! :-1:

**Comment by etianen** [comment]
Just to confirm:

* The `django.contrib.auth` app is listed before the `falcon_app.apps.FalconAppConfig` app in `INSTALLED_APPS`.
* In your `falcon_app.apps.admin.py` file you have:

    ``` py
    from django.contrib import admin
    from django.contrib.auth.models import User
    from django.contrib.auth.admin import UserAdmin

    admin.site.unregister(User)

    @admin.register(User)
    class VersionUserAdmin(VersionAdmin, UserAdmin):

        pass
    ```

If that's giving you an error, then please can I have the full traceback of the error?

**Comment by guganselvaraj** [comment]
Heres trace back ! 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/eindhan/PROJECT-FALCON/falcon/falcon_app/admin.py", line 17, in <module>
    admin.site.unregister(User)
  File "/home/eindhan/falcon/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model User is not registered

**Comment by etianen** [comment]
Excellent!
