### ISSUE TITLE
LookupError: No installed app with label

### ISSUE THREAD

**Issue by Visgean** [etianen/django-reversion#543]
Hi, when I try to migrate to latest version I get a following error:

```
Running migrations:
  Rendering model states... DONE
  Applying reversion.0003_auto_20160601_1600...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 148, in get_app_config
    return self.app_configs[app_label]
KeyError: 'voting'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/reversion/migrations/0003_auto_20160601_1600.py", line 43, in set_version_db
    model = apps.get_model(app_label, model_name)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 197, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 155, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'voting'.

```

Now this is mentioned in https://docs.djangoproject.com/en/dev/topics/migrations/#accessing-models-from-other-apps it seems that this https://github.com/etianen/django-reversion/blob/master/reversion/migrations/0003_auto_20160601_1600.py#L45 piece of code tries to work with the models... this is my model for reference: https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/voting/models.py#L15

any idea what is happening here?

**Comment by etianen** [comment]
Check out the master branch. It might be fixed.

Basically, a migration is supposed to declare up-front which apps it needs to access, and this migration needs to access ALL the apps in your project. So I've switched to using the live models, rather than the snapshot models. This is normally a bad idea, but for the purpose of this revision, which simply needs to look up the write DB of the model, it should be fine.

**Comment by chris-erickson** [comment]
I'm seeing the same error using `2.0.4`.  It's referencing an app that I don't even have, but potentially existed on my local dev instance at some point while I was building an app.  It's possible I renamed that app in the course of local development.

**Comment by etianen** [comment]
Hum... so it's a stale reference to an app. Normally those content types
would be cleaned out the database automatically.

I guess this case should be handled. I'll have a look at the start of next
week.

**Comment by etianen** [comment]
Okay, have a try with the master branch.

**Comment by tdruez** [comment]
@etianen your last 1f256b4db56ca771a3951bed74574ce4e5da1e86 commit solved the `LookupError: No installed app` on my side.
Thanks!

**Comment by etianen** [comment]
Cool, I'll push a new patch release tomorrow.

Thanks for letting me know!

**Comment by etianen** [comment]
2.0.5 is now out.

**Comment by tdruez** [comment]
@etianen 👍  for 2.0.5, working fine on my side.
