### ISSUE TITLE
createinitialrevisions not working with admin.site.register_view 

### ISSUE THREAD

**Issue by aldarund** [etianen/django-reversion#587]
If i  have any admin.site.register_view in my admin.py createinitialrevisions  just fails with a error  'AdminSite' object has no attribute 'register_view'

```
 python manage.py createinitialrevisions
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/reversion/management/commands/createinitialrevisions.py", line 36, in handle
    for model in self.get_models(options):
  File "/usr/local/lib/python2.7/dist-packages/reversion/management/commands/__init__.py", line 31, in get_models
    admin.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/rentapplication/django-rentapplication/rentapplication/admin.py", line 207, in <module>
    admin.site.register_view('log_in_as_user', name="Log In As User", view=log_in_as_user, urlname="log_in_as_user")
AttributeError: 'AdminSite' object has no attribute 'register_view'
```

Is there a workaround for this? I cant really comment out every of this on production just to run createinitialrevisions  

django 1.8

**Comment by aldarund** [comment]
It happening when using https://pypi.python.org/pypi/django-adminplus
And it happens because for django adminplus you need replace admin.site with a object from django-adminplus. And it happens in urls.py. But django-reversion just import admin in the management command here
https://github.com/etianen/django-reversion/blob/master/reversion/management/commands/__init__.py#L31
so it use standard one site object so this error will happen.

**Comment by etianen** [comment]
This is something to do with django-adminplus, not reversion. It looks like
register_view is created dynamically.

django-reversion's management commands do nothing special. It looks like
django-adminplus is breaking management commands in general.
