### ISSUE TITLE
Migration from 1.9.3 to 2.0.7

### ISSUE THREAD

**Issue by jfscyberpub** [etianen/django-reversion#604]
Hi,

I have been trying to update django-version from **1.9.3** to **2.0.7** and I got this error:
`django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 1000 bytes')`

This happened during migration **0004_auto_20160611_1202**

I'm using **Django==1.8.12** with **Python 2.7.12** and **MySQL 5.7.16**. MySQL engine is MyISAM.

How can I fix this issue ? Please advise. Thank you.

Here is the stacktrace:

```
  Applying reversion.0004_auto_20160611_1202...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 324, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/jonathan/projects/venvs/tool2/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 1000 bytes')
```

**Comment by etianen** [comment]
You need to change your database engine to InnoDB. That should solve the
migration issue.

Incidentally, if you try to use the reversion admin with MyISAM, you're
going to hit a nasty data duplication issue, since MyISSAM doesn't support
transactions.

**Comment by jfscyberpub** [comment]
@etianen I'm going to give a try. Thanks.

**Comment by jfscyberpub** [comment]
It worked! Thank you.

For those who are interested or meet the same issue, just those SQL command:

```
ALTER TABLE reversion_revision ENGINE=InnoDB;
ALTER TABLE reversion_version ENGINE=InnoDB;
```

**Comment by etianen** [comment]
Excellent! Please ensure that you're using InnoDB for all model tables
controlled by reversion too, or you'll get a nasty suprise when using the
admin integration!

**Comment by tomviner** [comment]
For the reference of others having this issue, but finding changing storage engine a daunting task for a large project, this is our workaround: https://github.com/sohonetlabs/django-reversion/pull/1

Note: this only works because we haven't run migration 0003 on our production database yet.
