### ISSUE TITLE
_Str object AttributeError

### ISSUE THREAD

**Issue by hesamedgh** [etianen/django-reversion#609]
hello guys!
I have an issue when trying to run create initial revisions, after installing and migrating the package.
the error is "AttributeError: '_Str' object has no attribute 'null'". 
Full Error:
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/reversion/management/commands/createinitialrevisions.py", line 51, in handle
    "object_id",
  File "/usr/local/lib/python3.4/dist-packages/reversion/models.py", line 317, in _safe_subquery
    "{}__in".format(left_field_name): right_subquery,
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 686, in exclude
    return self._filter_or_exclude(True, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 695, in _filter_or_exclude
    clone.query.add_q(~Q(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 1222, in build_filter
    self.is_nullable(targets[0]) or
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 2039, in is_nullable
    return field.null
AttributeError: '_Str' object has no attribute 'null'`

it seems that its caused by calling _safe_subquery() in get_deleted of VersionQuerySet. it runs is_nullable on _Str object and raises the error.

cant figure out how to solve this, any help is appreciated!
tnx!

**Comment by etianen** [comment]
This seems be related to #606

This is very mysterious. That line is covered by unit tests. What version of Django are you using?

**Comment by luko82** [comment]
Hi! 
I think I'm having the same error. My django version is 1.8.2 and i recently updated to django-reversion 2.0.8

`  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "ENV2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "ENV2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "ENV2/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "ENV2/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "ENV2/local/lib/python2.7/site-packages/reversion/management/commands/createinitialrevisions.py", line 51, in handle
    "object_id",
  File "ENV2/local/lib/python2.7/site-packages/reversion/models.py", line 317, in _safe_subquery
    "{}__in".format(left_field_name): right_subquery,
  File "ENV2/local/lib/python2.7/site-packages/django/db/models/query.py", line 686, in exclude
    return self._filter_or_exclude(True, *args, **kwargs)
  File "local/lib/python2.7/site-packages/django/db/models/query.py", line 695, in _filter_or_exclude
    clone.query.add_q(~Q(*args, **kwargs))
  File "ENV2/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1304, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "ENV2/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1332, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "ENV2/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    self.is_nullable(targets[0]) or
  File "ENV2/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 2044, in is_nullable
    return field.null
AttributeError: '_Str' object has no attribute 'null'
`

Thanks in advance

**Comment by luko82** [comment]
If i downgrade to django-reversion 2.0.6 it seems to work. At least, the initial revisions are created without any problem.

**Comment by etianen** [comment]
Could you try to upgrading to the latest Django 1.8.17, and see if it
works? This feels like a bug in Django, and I only test against the latest
bugfix release in each minor django release.
