### ISSUE TITLE
Error on createinitialrevisions, I think because of null dates on model

### ISSUE THREAD

**Issue by sschloesser** [etianen/django-reversion#632]
I get the following error message when running `createinitialrevisions`: 
```
return '' if val is None else val.isoformat() 
AttributeError: 'unicode' object has no attribute 'isoformat'
```
I believe it may be because on the model where the error occurred there is a date field that is allowed to be null, so maybe it's trying to call isoformat() on it. Other models with non-nullable dates went through without issues.

**Comment by etianen** [comment]
Can I have a full stack trace, please?

**Comment by sschloesser** [comment]
```
(siscon) sebastian@Tatan ~/src/siscon $ python manage.py createinitialrevisions
Creating revisions for casa
- Created 360 / 360
Creating revisions for cliente
- Created 627 / 627
Creating revisions for Pedido
- Created 16169 / 16169
Creating revisions for confirmacion
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/reversion/management/commands/createinitialrevisions.py", line 62, in handle
    add_to_revision(obj, model_db=model_db)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/reversion/revisions.py", line 212, in add_to_revision
    _add_to_revision(obj, db, model_db, True)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/reversion/revisions.py", line 191, in _add_to_revision
    fields=version_options.fields,
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/core/serializers/base.py", line 88, in serialize
    self.handle_field(obj, field)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/core/serializers/python.py", line 54, in handle_field
    self._current[field.name] = field.value_to_string(obj)
  File "/Users/sebastian/.virtualenvs/siscon/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1285, in value_to_string
    return '' if val is None else val.isoformat()
AttributeError: 'unicode' object has no attribute 'isoformat'
```

and here is the model
```
class Confirmacion(models.Model):
    ID = models.CharField(max_length=15, unique=True, primary_key=True, editable=False)
    id_pedido = models.ForeignKey(Pedido, on_delete=models.PROTECT)
    fecha_confirmacion = models.DateField()
    fecha_despacho = models.DateField()
    fecha_firmada = models.DateField(blank=True, null=True)
    vuelo_buque = models.CharField(max_length=25)
    awb_booking = models.CharField(max_length=25)
    etd = models.DateField(verbose_name='ETD')
    eta = models.DateField(verbose_name='ETA')
```

**Comment by etianen** [comment]
Could you do a little experiment for me, and make that null date field not
null, and see if the problem goes away.

I'm thinking that this is a bug in the Django serialization framework, as
it stands.

**Comment by sschloesser** [comment]
But what about all the rows in the DB that already have that field NULL, I'd have to fill them in with a  default value. I'm pretty sure that's the problem, though, do you know how you could perhaps override the serializer?

**Comment by etianen** [comment]
I've dug into this a bit deeper.

You're getting the error because `fecha_firmada` contains a `unicode` value. This should never happen, because it's a date field, so should only contain values of type `datetime` or `None`. For a unicode string to get in there, something has gone awry.

So the question is, how is a unicode value getting into the date field? Is that the full definition of the `Confirmacion` model, or is there other stuff (methods, etc) there that I haven't seen?

**Comment by sschloesser** [comment]
Wow! I just looked at my DB with navicat and that field is indeed a varchar 😱 I went through all of my migrations and the only time it appeared was in the initial creation `('fecha_firmada', models.DateField(blank=True, null=True)),` Maybe this is a django bug involving null dates? 

In case it's still interesting to you, this is the only other stuff I had on the model, which I don't think is affecting this
```
    def save(self, *args, **kwargs):
        if not self.ID:
            prefix = self.id_pedido.id_pedido[:2]
            self.ID = next_pk(Confirmacion, prefix)
        super(Confirmacion, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s' % self.ID
    def __str__(self):
        return '%s' % self.ID

    class Meta:
        verbose_name_plural = 'Confirmaciones'
```

**Comment by etianen** [comment]
If that field is a varchar, then that is indeed the source of the bug!

This does sound like a Django bug, indeed! I'd suggest reporting it on the
Django project issue tracker.

**Comment by sschloesser** [comment]
Changed it back to date and `createinitialrevisions` ran perfectly. Thanks for your help figuring this out!
