### ISSUE TITLE
Savepoints on POST requests. Error if atomic(savepoint=False)

### ISSUE THREAD

**Issue by guettli** [etianen/django-reversion#680]
We discovered that your django postgres db connection uses savepoints on POST requests.

We discovered that django-reversion begins the transactions if the request is a POST request.

After the middlewares were processed, the django does atomic() since atomic views are enabled.

AFAIK savepoints make postgres a bit slower, and that's why we used atomic(savepoint=False).

But if we do this, we get this exception:
```

Traceback (most recent call last):
  File "/.../lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/.../lib/python2.7/site-packages/reversion/middleware.py", line 44, in process_response
    self._close_revision(request, False)
  File "/.../lib/python2.7/site-packages/reversion/middleware.py", line 41, in _close_revision
    request._revision_middleware.pop(self).__exit__(*sys.exc_info() if is_exception else (None, None, None))
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 317, in __exit__
    return self._context.__exit__(exc_type, exc_value, traceback)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 294, in _create_revision_context
    using=using,
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 232, in _save_revision
    for model, db_pks in model_db_pks.items()
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 232, in <dictcomp>
    for model, db_pks in model_db_pks.items()
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 230, in <dictcomp>
    for db, pks in db_pks.items()
TypeError: argument 2 to map() must support iteration

```

What could go wrong, if atomic(savepoint=False) gets used to avoid savepoints?

**Comment by guettli** [comment]
If I use two for-loops instead of a dict comprehension, then I see better error message:

```

  File "/.../lib/python2.7/site-packages/rest_framework/test.py", line 161, in request
    return super(APIClient, self).request(**kwargs)
  File "/.../lib/python2.7/site-packages/rest_framework/test.py", line 113, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/.../lib/python2.7/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/.../lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/.../lib/python2.7/site-packages/reversion/middleware.py", line 44, in process_response
    self._close_revision(request, False)
  File "/.../lib/python2.7/site-packages/reversion/middleware.py", line 41, in _close_revision
    request._revision_middleware.pop(self).__exit__(*sys.exc_info() if is_exception else (None, None, None))
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 323, in __exit__
    return self._context.__exit__(exc_type, exc_value, traceback)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 300, in _create_revision_context
    using=using,
  File "/.../lib/python2.7/site-packages/reversion/revisions.py", line 226, in _save_revision
    for instance in model._default_manager.using(db).filter(pk__in=pks).values_list("pk", flat=True):
  File "/.../lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/.../lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/.../lib/python2.7/site-packages/django/db/models/query.py", line 155, in __iter__
    for row in compiler.results_iter():
  File "/.../lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 789, in results_iter
    results = self.execute_sql(MULTI)
  File "/.../lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/.../lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/.../lib/python2.7/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/.../lib/python2.7/site-packages/django/db/backends/base/base.py", line 428, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

```

**Comment by guettli** [comment]
I found a patch to revision.py. If the connection needs a rollback, then don't save on it:
```

--- tmp/revisions.py	2017-11-21 17:34:14.269977880 +0100
+++ /home/modwork_gew_di1485/lib/python2.7/site-packages/reversion/revisions.py	2017-11-21 17:35:07.101961248 +0100
@@ -14,6 +14,7 @@
 from reversion.compat import remote_field
 from reversion.errors import RevisionManagementError, RegistrationError
 from reversion.signals import pre_revision_commit, post_revision_commit
+from django.db import connections
 
 
 _VersionOptions = namedtuple("VersionOptions", (
@@ -283,7 +284,7 @@
         with context:
             yield
             # Only save for a db if that's the last stack frame for that db.
-            if not any(using in frame.db_versions for frame in _local.stack[:-1]):
+            if (not connections[using].needs_rollback) and not any(using in frame.db_versions for frame in _local.stack[:-1]):
                 current_frame = _current_frame()
                 _save_revision(
                     versions=current_frame.db_versions[using].values(),

```

What do you think?

**Comment by etianen** [comment]
If you're using atomic() without savepoints, then any code that runs after
your failed database query will run into this error. Fixing it in reversion
is a band-aid.

You should just use atomic with savepoints (the default), as django
recommends. Alternatively, call rollback() manually yourself when you catch
the error.

**Comment by guettli** [comment]
Yes, you are right. But doing a savepoint for every POST request seems strange to me. I don't know the overhead of it, but it feels useless and superfluous. But of course this is not something which needs to be discussed in this issue.

AFAIK it would not hurt, if reversion would check the state of the connection before using it in process_response().

**Comment by etianen** [comment]
It’s doing a transaction on every post request because the middleware needs
to group the revision data with the model save(). Otherwise, your database
can get into an inconsistent state.

The middleware isn’t particularly efficient as a result, but it is
convenient. If you want efficiency, use explicit reversion.revision()
decorators. This is just like the Django ATOMIC_REQUESTS feature, in that
regard.

Checking for the transaction being dirty isn’t harmful, but it is extra
complexity, and would only help people who go against the Django advice of
using atomic(savepoint=False).

Using the inefficient revision middleware totally eclipses any minor
performance gain from using atomic(savepoint=False) elsewhere in your
codebase. Making the inefficient middleware more complex to support a micro
optimisation seems very counter intuitive, to me.

Just use atomic(savepoint=True)!

**Comment by pnuckowski** [comment]
Hi guys,

unfortunately this transaction.atomic on POST request causes that our process fail.

example: 
incoming request that creates new model and enqueues async job (rq or celery) that takes newly created model id as a argument. The enqueued job fetches from database particular model to work on, but it fails with `ObjectDoesNotExist` because transaction wasn"t yet commited (worker starts working on job, before request was finished).


I think described example is very common across many applications, so maybe it should be somehow fixed :)

**Comment by etianen** [comment]
The solution is to use the transaction.on_commit() feature in Django:

https://docs.djangoproject.com/en/2.0/topics/db/transactions/#performing-actions-after-commit

Alternatively, use manual reversion.create_revision() calls in your code,
and don't use the middleware.

Alternatively, subclass RevisionMiddleware and set atomic = False on it.
Then use that middleware. This "fix" leads to data integrity issues,
however, which is why reversion uses a transaction!
