### ISSUE TITLE
REVERT opportunity with CBV in django-reversion app?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [etianen/django-reversion#687]
I use next CBV to revert to a specific version of a record. Unfortunately it raise error. I am little bit confused. Can you say whats the reason? Problem in my CBV or in django-reversion?

**views.py:**
```
from reversion.views import RevisionMixin
from django.views import View
from django.shortcuts import get_object_or_404, redirect
from reversion.models import Version
import reversion

class ArticleRevert(RevisionMixin, View):
    def get(self, request, *args, **kwargs):
        article=get_object_or_404(Article, pk=self.kwargs.get('pk'))
        revision=get_object_or_404(Version.objects.get_for_object(article), pk=self.kwargs.get('article_reversion_id')).revision
        reversion.set_comment("Revert to version #{}".format(revision.id))
        revision.revert()
        return redirect('article_list')
```

**ERROR:**
```
Traceback (most recent call last):
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/reversion/views.py", line 43, in do_revision_view
    return func(request, *args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Applications/Projects/web/project/article/views.py", line 165, in get
    reversion.set_comment("Revert to version #{}".format(reversion.id))
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/reversion/revisions.py", line 122, in set_comment
    _update_frame(comment=comment)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/reversion/revisions.py", line 87, in _update_frame
    _local.stack = _local.stack[:-1] + (_current_frame()._replace(**kwargs),)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/reversion/revisions.py", line 53, in _current_frame
    raise RevisionManagementError("There is no active revision for this thread")
RevisionManagementError: There is no active revision for this thread
```

**Comment by etianen** [comment]
Could you clarify what "next CBV" is?

**Comment by NogerbekNurzhan** [comment]
CBV - Class Based View. In my case its ArticleRevert.

**Comment by etianen** [comment]
Thanks!

Decorate your get() method with reversion.create_revision().

**Comment by NogerbekNurzhan** [comment]
It works now but it seems to me that its dirty solution.

Before I thought that `@reversion.create_revision()` we can use only in Function Based View and in Class Based View we need to use only RevisionMixin. Isn't that right?

**Comment by etianen** [comment]
It's not dirty, it's exactly the was django's transaction.atomic() is
supposed to be used.

HOWEVER, I didn't notice that you were using RevisionMixin! So that
requires some more explanation.

RevisionMixin only does not create a revision for GET, HEAD or OPTIONS
request methods, since those are supposed to be "safe", and not modify
data. You can get around this by using the reversion.create_revision()
decorator manually, or by using a more appropriate HTTP method.
