### ISSUE TITLE
ModuleNotFoundError: No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by chang-brian** [etianen/django-reversion#767]
Does django-reversion support Django 2.0 and 2.1? There's still a reference to `django.core.urlresolvers` rather than `django.urls`.

`Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/reversion/management/commands/createinitialrevisions.py", line 58, in handle
    for model in self.get_models(options):
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/reversion/management/commands/__init__.py", line 31, in get_models
    admin.autodiscover()
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/brian/.local/share/virtualenvs/jyve-django-94mtg9Ra/lib/python3.6/site-packages/adminsortable2/admin.py", line 9, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'`

This happens when I run `./manage.py createinitialrevisions`

**Comment by claudep** [comment]
I would suggest to close this issue.
