### ISSUE TITLE
Suggestion: Add note on serialized_rollback = True for TransactionTestCase or LiveServerTestCase

### ISSUE THREAD

**Issue by torbjoernk** [etianen/django-reversion#779]
**I suggest to add a note to the documentation of django-reversion when used in combination with [TransactionTestCase](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#transactiontestcase) or [LiveServerTestCase](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#liveservertestcase) in order to enable `serialized_rollback`.**

I just spend several hours debugging the failure of my Selenium-driven LiveServerTestCases as soon as a django-reversion-registered model was created within such a test case.

With the following scaffold of the test case:
```{.py}
class MyViewLiveTest(LiveServerTestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.selenium = Chrome(options.binary_location)
        cls.selenium.implicitly_wait(10)

    @classmethod
    def tearDownClass(cls):
        cls.selenium.quit()
        super().tearDownClass()

    @tag('selenium')
    def test_create_versioned_model(self):
        with reversion.create_revision():
            MyModel.objects.create(foo='bar')
```
On class tear down I was presented the following error:
```
python manage.py test --tag=selenium requirements
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

Error
Traceback (most recent call last):
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/test/testcases.py", line 209, in __call__
    self._post_teardown()
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/test/testcases.py", line 908, in _post_teardown
    self._fixture_teardown()
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/test/testcases.py", line 943, in _fixture_teardown
    inhibit_post_migrate=inhibit_post_migrate)
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/core/management/commands/flush.py", line 80, in handle
    emit_post_migrate_signal(verbosity, interactive, database)
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/contrib/auth/management/__init__.py", line 79, in create_permissions
    Permission.objects.using(using).bulk_create(perms)
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/models/query.py", line 471, in bulk_create
    obj_without_pk._state.db = self.db
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/transaction.py", line 212, in __exit__
    connection.commit()
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/backends/base/base.py", line 261, in commit
    self._commit()
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/john/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: FOREIGN KEY constraint failed

Destroying test database for alias 'default'...

Process finished with exit code 1
```

The fix is to set `serialized_rollback = True` in the LiveServerTestCase class as documented [in the warning box of the TransactionTestCase API docu](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#transactiontestcase).

**Comment by etianen** [comment]
I'm confused about why django-reversion needs serialized rollback. It has
no data that needs to be reloaded. It works just fine with an empty
database.

**Comment by torbjoernk** [comment]
I did some further testing in order to provide more information.

My current project with which I have this problem is using Djanog 2.1.7.

I was not able to reproduce this error with a newly set up project.

However, stripping down my current project to a point where the only model was not using any foreign keys but had reversion enabled, still had that issue. The minimal demo project - from my point of view and limited insight into Django's internals - had the same structure and general functionality.

Upgrading my current project to Django 2.2b1 made the issue disappear. As my project is far from production ready, I'll stick with Django 2.2b1 and django-reversion 3.0.3.

Sorry for the noise.
