### ISSUE TITLE
AttributeError: module 'reversion' has no attribute 'register'

### ISSUE THREAD

**Issue by dhenryFabrice** [etianen/django-reversion#871]
Hello,

I get a "AttributeError: module 'reversion' has no attribute 'register'" when I run "manage.py makemigrations"
django 3.2
django reversion 3.0.9
code:
# Create your models here.
@reversion.register()
class Service(models.Model):
    title = models.CharField(max_length=50)

    description = models.TextField(blank=True)

    published = models.BooleanField(default=False)
blabla
...

Best regards

**Comment by etianen** [comment]
Can I have the full traceback?

**Comment by dhenryFabrice** [comment]
Hello,

Yes: 

python manage.py makemigrations
Traceback (most recent call last):
  File "/home/fabrice/PycharmProjects/escola/manage.py", line 22, in <module>
    main()
  File "/home/fabrice/PycharmProjects/escola/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/fabrice/PycharmProjects/escola/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/fabrice/PycharmProjects/escola/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/fabrice/PycharmProjects/escola/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/fabrice/PycharmProjects/escola/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/fabrice/PycharmProjects/escola/venv/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/fabrice/PycharmProjects/escola/cantina/models.py", line 12, in <module>
    @reversion.register()
AttributeError: module 'reversion' has no attribute 'register'


Many thanks for your help,

Regards

**Comment by etianen** [comment]
Very interesting. This implies reversion's import of Django is failing, so
it can't initialize it's own API.

Try editing the reversion source to print out the exception message here:
https://github.com/etianen/django-reversion/blob/master/reversion/__init__.py#L11
