### ISSUE TITLE
Postgres jsonb fields are not serializable.

### ISSUE THREAD

**Issue by anudeepsamaiya** [etianen/django-reversion#891]
**Versions**
Django==2.2
django-reversion==4.0.0

**Model:**
```
from django.contrib.postgres.fields import ArrayField, JSONField
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
import reversion

@reversion.register(follow=["parent"], format="rule")
class Child(models.Model):
    parent = models.ForeignKey("my.models.Parent", on_delete=models.PROTECT, null=True)
    data = ArrayField(
        JSONField(encoder=DjangoJSONEncoder),
        max_length=200,
        blank=True,
        default=list,
    )

```

**Example Data**
```
{'rule_condition_type': 1, 'risk_types': [1], 'entity_types': [10], 'threshold_amount_usd': Decimal('0'), 'taint_percent_threshold': Decimal('0')}
```

**Traceback**

```
Original exception was:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 943, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/site-packages/reversion/revisions.py", line 330, in _post_save_receiver
    add_to_revision(instance, model_db=using)
  File "/usr/local/lib/python3.6/site-packages/reversion/revisions.py", line 215, in add_to_revision
    _add_to_revision(obj, db, model_db, True)
  File "/usr/local/lib/python3.6/site-packages/reversion/revisions.py", line 194, in _add_to_revision
    use_natural_foreign_keys=version_options.use_natural_foreign_keys,
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py", line 107, in serialize
    self.handle_field(obj, field)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/python.py", line 50, in handle_field
    self._current[field.name] = self._value_from_field(obj, field)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/python.py", line 47, in _value_from_field
    return value if is_protected_type(value) else field.value_to_string(obj)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/postgres/fields/array.py", line 132, in value_to_string
    return json.dumps(values)
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Decimal' is not JSON serializable

```

This error only appears when used with `reversion.register` decorator, otherwise it works fine with drf serializers.

**Comment by anudeepsamaiya** [comment]
@etianen there should be a provision to use custom serializers. What do you think? One can be supplied in `register` options

**Comment by etianen** [comment]
This is nothing to do with django-reversion. The
`django.contrib.postgres.ArrayField` serializes using the default
`json.dumps` encoder. You should raise a ticket on the Django issue tracker
asking for this feature.

Meanwhile, you can work around this by converting all Decimal to string
before serialization, or by writing your own django serializer and
specifying it using the "format" argument for reversion.register.

https://django-reversion.readthedocs.io/en/stable/api.html#registration-api

**Comment by anudeepsamaiya** [comment]
Yeah I did raised a [ticket](https://code.djangoproject.com/ticket/33086) there. But apparently it wont be fixed for other reasons.
