### ISSUE TITLE
Error: 'HttpResponseRedirect' object has no attribute 'render'

### ISSUE THREAD

**Issue by tulgaab** [etianen/django-reversion#906]
Just tried to recover deleted object. But that error was thrown. How to fix it?

`Internal Server Error: /admin/redrock/roomtype/recover/7/
Traceback (most recent call last):
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/reversion/admin.py", line 206, in recover_view
    return self._reversion_revisionform_view(
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/reversion/admin.py", line 183, in _reversion_revisionform_view
    response.render()  # Eagerly render the response, so it's using the latest version.
AttributeError: 'HttpResponseRedirect' object has no attribute 'render'`

**Comment by CiaranSanders** [comment]
Hi I've been running into this error as well, and so far have not found a solution. Were you able to figure out anything?

**Comment by stuartaccent** [comment]
for anyone visiting here,

i just had the same thing. for me it was due to the model being a proxy model and not setting the `for_concrete_model=False` when registering the model in the admin. I have several models all proxy from the same base. they all had the concrete model's content type in there version. but were trying to load a record in the recover view they were actually trying to load based on one of the other proxy's content type and getting a redirect does not exist. (i believe)

i don't know if this behaviour is expected or not but setting `for_concrete_model=False` fixed it for me.

https://django-reversion.readthedocs.io/en/stable/api.html?highlight=proxy#registration-api

Stu.
