### ISSUE TITLE
createinitialrevision fails with iterator error (reversion 4.0.2, Django 3.2)

### ISSUE THREAD

**Issue by nikhaldi** [etianen/django-reversion#923]
After updating from django-reversion 4.0.1 to 4.0.2 my creatinitialrevision commands started failing with this exception:

```
 Traceback (most recent call last):
   File "/home/app/./manage.py", line 32, in <module>
    main()
  File "/home/app/./manage.py", line 28, in main
     execute_from_command_line(sys.argv)
   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
     utility.execute()
   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
     output = self.handle(*args, **options)
   File "/home/app/apps/base/management/commands/predeploy.py", line 18, in handle
     call_command("createinitialrevisions")
   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
     return command.execute(*args, **defaults)
   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
     output = self.handle(*args, **options)
   File "/usr/local/lib/python3.9/site-packages/reversion/management/commands/createinitialrevisions.py", line 81, in handle
     for obj in live_objs.iterator(batch_size):
 TypeError: iterator() takes 1 positional argument but 2 were given
```

I assume that it's a combination of dependency versions that leads to this problem so here's key dependencies:

- Python: 3.9.7
- django-reversion: 4.0.2
- Django: 3.2.15
- psycopg2-binary: 2.9.3

Haven't dug further than this. Any ideas?

**Comment by etianen** [comment]
This is really odd and I can't reproduce it.

Can you try adding a `print(type(live_objs))` right before the offending line in `createinitialrevisions`?

I'm wondering if some 3rd party code is messing with the queryset.
